Etapa 1: Contextualização e Formulação da Pergunta
Apresente a origem dos dados, o contexto temático e a relevância do problema
investigado.

(escrever)

Declare formalmente a variável alvo () que você deseja prever e descreva o
significado de cada uma das variáveis de entrada () selecionadas.

(escrever)

Justifique formalmente a escolha do tipo de aprendizado (Regressão ou
Classificação), conectando-a à natureza da variável de saída.

(escrever)

O nosso problema analítico exige uma abordagem de Regressão, já que o que será analisado é: 'O que faz uma música ter uma alta danceability?'
E nesse caso era iria prever o quanto a música(x) tem de danceability.  (rascunho)

In [ ]:

pip install pandas numpy matplotlib seaborn scikit-learn

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.linear_model import LinearRegression

Etapa 2: Exploração e Engenharia de Dados

In [8]:
df=pd.read_csv('songs_normalize.csv')
display(df.head()) #exibindo as primeiras 5 linhas

,artist,song,duration_ms,explicit,year,popularity,danceability,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.751,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop
1,blink-182,All The Small Things,167066,False,1999,79,0.434,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Faith Hill,Breathe,250546,False,1999,66,0.529,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country"
3,Bon Jovi,It's My Life,224493,False,2000,78,0.551,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal"
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.614,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop

In [ ]:

#verificando o tamanho da base
print("Linhas e colunas:", df.shape)
#verificando os tipos das colunas
print(df.dtypes)

Linhas e colunas: (2000, 18)
artist                  str
song                    str
duration_ms           int64
explicit               bool
year                  int64
popularity            int64
danceability        float64
energy              float64
key                   int64
loudness            float64
mode                  int64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
genre                   str
dtype: object
artist              0
song                0
duration_ms         0
explicit            0
year                0
popularity          0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
genre               0
dtype: int64

In [ ]:
#valores nulos
print(df.isnull().sum())

artist              0
song                0
duration_ms         0
explicit            0
year                0
popularity          0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
genre               0
dtype: int64

In [ ]:
#verificando linhas duplicadas
print("Linhas duplicadas:", df.duplicated().sum())

Linhas duplicadas: 59

In [15]:
#removendo linhas duplicadas
df = df.drop_duplicates()
#verificando linhas duplicadas(novamente)
print("Linhas duplicadas:", df.duplicated().sum())

Linhas duplicadas: 0

In [ ]:
#definindo a coluna que queremos prever
coluna_alvo = 'danceability'
#separando os atributos e a resposta
X = df.drop(columns=[coluna_alvo])
y = df[coluna_alvo]
#visualizando os atributos
display(X.head())
#visualizando a resposta
display(y.head())
#conferindo os tamanhos
print('Tamanho de X:', X.shape)
print('Tamanho de y:', y.shape)

,artist,song,duration_ms,explicit,year,popularity,energy,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,genre
0,Britney Spears,Oops!...I Did It Again,211160,False,2000,77,0.834,1,-5.444,0,0.0437,0.3000,0.000018,0.3550,0.894,95.053,pop
1,blink-182,All The Small Things,167066,False,1999,79,0.897,0,-4.918,1,0.0488,0.0103,0.000000,0.6120,0.684,148.726,"rock, pop"
2,Faith Hill,Breathe,250546,False,1999,66,0.496,7,-9.007,1,0.0290,0.1730,0.000000,0.2510,0.278,136.859,"pop, country"
3,Bon Jovi,It's My Life,224493,False,2000,78,0.913,0,-4.063,0,0.0466,0.0263,0.000013,0.3470,0.544,119.992,"rock, metal"
4,*NSYNC,Bye Bye Bye,200560,False,2000,65,0.928,8,-4.806,0,0.0516,0.0408,0.001040,0.0845,0.879,172.656,pop

0    0.751
1    0.434
2    0.529
3    0.551
4    0.614
Name: danceability, dtype: float64

Tamanho de X: (1941, 17)
Tamanho de y: (1941,)

Etapa 3: Particionamento dos Dados (Treino e Teste)

Etapa 4: Construção e Treinamento do Modelo

Etapa 5: Avaliação Quantitativa e Diagnóstico Visual

Etapa 6: Simulador Interativo (Inferência com Entrada do Usuário)

Etapa 7: Discussão Crítica e Conclusões

1. Interpretação das Métricas: O que os resultados numéricos revelam sobre a
eficácia prática do modelo? Ele é confiável para tomada de decisão real?

(escrever)

2. Diagnóstico dos Erros:

○ Caso Regressão: A diferença entre MAE e RMSE aponta presença de
desvios atípicos acentuados? O que o peso de cada variável revela sobre a
importância delas?

(escrever)

3. Limitações: Quais fatores ou variáveis adicionais não presentes na sua base
original poderiam elevar a precisão do sistema se estivessem disponíveis?

(escrever)